export type StatusCodeCategory = "Informational" | "Success" | "Redirection" | "Client Error" | "Server Error";

export interface HttpStatusCode {
    code: number;
    message: string;
    description: string;
    category: StatusCodeCategory;
    useCase?: string;
}

export const HTTP_STATUS_CODES: HttpStatusCode[] = [
    // 1xx Informational
    { code: 100, message: "Continue", category: "Informational", description: "The server has received the request headers and the client should proceed to send the request body.", useCase: "Used when sending large payloads to check if the server will accept it before transmitting the whole body." },
    { code: 101, message: "Switching Protocols", category: "Informational", description: "The requester has asked the server to switch protocols and the server has agreed to do so.", useCase: "Used when upgrading an HTTP connection to a WebSocket connection." },
    { code: 102, message: "Processing", category: "Informational", description: "A WebDAV request may contain many sub-requests involving file operations, requiring a long time to complete the request.", useCase: "Prevents the client from timing out while the server is processing a complex WebDAV request." },
    { code: 103, message: "Early Hints", category: "Informational", description: "Used to return some response headers before final HTTP message.", useCase: "Helps the client preload resources (like CSS or JS) while the server is still preparing the main response." },

    // 2xx Success
    { code: 200, message: "OK", category: "Success", description: "Standard response for successful HTTP requests.", useCase: "The most common response for successful GET, PUT, or POST requests." },
    { code: 201, message: "Created", category: "Success", description: "The request has been fulfilled, resulting in the creation of a new resource.", useCase: "Typically returned after a successful POST request that creates a new database record." },
    { code: 202, message: "Accepted", category: "Success", description: "The request has been accepted for processing, but the processing has not been completed.", useCase: "Used for asynchronous operations, like triggering a background job or video encoding." },
    { code: 203, message: "Non-Authoritative Information", category: "Success", description: "The server is a transforming proxy (e.g. a Web accelerator) that received a 200 OK from its origin, but is returning a modified version of the origin's response.", useCase: "Used when a proxy alters the response headers from the origin server." },
    { code: 204, message: "No Content", category: "Success", description: "The server successfully processed the request and is not returning any content.", useCase: "Commonly used for successful DELETE or PUT requests where the client doesn't need to navigate away from its current page." },
    { code: 205, message: "Reset Content", category: "Success", description: "The server successfully processed the request, but is not returning any content. The client should reset the document view.", useCase: "Used when submitting a form to tell the browser to clear the form fields." },
    { code: 206, message: "Partial Content", category: "Success", description: "The server is delivering only part of the resource due to a Range header sent by the client.", useCase: "Used for resumable downloads or video streaming." },
    { code: 207, message: "Multi-Status", category: "Success", description: "The message body that follows is by default an XML message and can contain a number of separate response codes.", useCase: "Used in WebDAV to return status for multiple independent operations." },
    { code: 208, message: "Already Reported", category: "Success", description: "The members of a DAV binding have already been enumerated in a preceding part of the (multistatus) response, and are not being included again.", useCase: "WebDAV optimization to avoid sending redundant data." },
    { code: 226, message: "IM Used", category: "Success", description: "The server has fulfilled a GET request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.", useCase: "Used in HTTP Delta encoding to send only the differences in a file." },

    // 3xx Redirection
    { code: 300, message: "Multiple Choices", category: "Redirection", description: "Indicates multiple options for the resource from which the client may choose.", useCase: "Used when presenting different format options for a video or document." },
    { code: 301, message: "Moved Permanently", category: "Redirection", description: "This and all future requests should be directed to the given URI.", useCase: "Used for SEO when migrating a website or permanently changing a URL structure." },
    { code: 302, message: "Found", category: "Redirection", description: "Tells the client to look at (browse to) another URL. The HTTP method may change to GET.", useCase: "Used for temporary redirects where the original URL might be restored later." },
    { code: 303, message: "See Other", category: "Redirection", description: "The response to the request can be found under another URI using the GET method.", useCase: "Commonly used after a successful POST request to redirect the user to a success page (Post/Redirect/Get pattern)." },
    { code: 304, message: "Not Modified", category: "Redirection", description: "Indicates that the resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match.", useCase: "Used for browser caching to save bandwidth when a resource hasn't changed." },
    { code: 305, message: "Use Proxy", category: "Redirection", description: "The requested resource is available only through a proxy, the address for which is provided in the response.", useCase: "Deprecated. Was used to force a client to connect via a proxy." },
    { code: 307, message: "Temporary Redirect", category: "Redirection", description: "The request should be repeated with another URI; however, future requests should still use the original URI. The HTTP method must not change.", useCase: "Modern replacement for 302 that strictly prevents the client from changing a POST to a GET." },
    { code: 308, message: "Permanent Redirect", category: "Redirection", description: "The request and all future requests should be repeated using another URI. The HTTP method must not change.", useCase: "Modern replacement for 301 that strictly prevents the client from changing a POST to a GET." },

    // 4xx Client Error
    { code: 400, message: "Bad Request", category: "Client Error", description: "The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax).", useCase: "Used when an API receives invalid JSON or missing required parameters." },
    { code: 401, message: "Unauthorized", category: "Client Error", description: "Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided.", useCase: "Returned when a user tries to access a protected API endpoint without a valid token." },
    { code: 402, message: "Payment Required", category: "Client Error", description: "Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme.", useCase: "Rarely used, but sometimes seen in APIs when an account has exhausted its quota or needs payment." },
    { code: 403, message: "Forbidden", category: "Client Error", description: "The request contained valid data and was understood by the server, but the server is refusing action. Authentication will not help.", useCase: "Used when an authenticated user attempts to access a resource they do not have permissions for (e.g., a regular user trying to access an admin panel)." },
    { code: 404, message: "Not Found", category: "Client Error", description: "The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible.", useCase: "The most common error for broken links or missing API endpoints." },
    { code: 405, message: "Method Not Allowed", category: "Client Error", description: "A request method is not supported for the requested resource.", useCase: "Used when a client tries to POST to a route that only accepts GET requests." },
    { code: 406, message: "Not Acceptable", category: "Client Error", description: "The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.", useCase: "Used when a client requests JSON via the Accept header, but the server can only return XML." },
    { code: 407, message: "Proxy Authentication Required", category: "Client Error", description: "The client must first authenticate itself with the proxy.", useCase: "Used by proxy servers to require login before routing a request." },
    { code: 408, message: "Request Timeout", category: "Client Error", description: "The server timed out waiting for the request.", useCase: "Used when a client opens a connection but takes too long to send the HTTP request body." },
    { code: 409, message: "Conflict", category: "Client Error", description: "Indicates that the request could not be processed because of conflict in the current state of the resource.", useCase: "Used when trying to create a user with an email address that already exists." },
    { code: 410, message: "Gone", category: "Client Error", description: "Indicates that the resource requested is no longer available and will not be available again.", useCase: "Used instead of 404 to explicitly tell search engines a page has been intentionally removed." },
    { code: 411, message: "Length Required", category: "Client Error", description: "The request did not specify the length of its content, which is required by the requested resource.", useCase: "Used when a client sends a POST request without a Content-Length header." },
    { code: 412, message: "Precondition Failed", category: "Client Error", description: "The server does not meet one of the preconditions that the requester put on the request.", useCase: "Used in optimistic locking when an If-Match header doesn't match the current entity tag (eTag)." },
    { code: 413, message: "Payload Too Large", category: "Client Error", description: "The request is larger than the server is willing or able to process.", useCase: "Used when a user tries to upload an image that exceeds the maximum allowed file size." },
    { code: 414, message: "URI Too Long", category: "Client Error", description: "The URI provided was too long for the server to process.", useCase: "Used when a GET request has too many query parameters." },
    { code: 415, message: "Unsupported Media Type", category: "Client Error", description: "The request entity has a media type which the server or resource does not support.", useCase: "Used when a client sends XML but the API only accepts JSON." },
    { code: 416, message: "Range Not Satisfiable", category: "Client Error", description: "The client has asked for a portion of the file, but the server cannot supply that portion.", useCase: "Used when asking for bytes 1000-2000 of a file that is only 500 bytes long." },
    { code: 417, message: "Expectation Failed", category: "Client Error", description: "The server cannot meet the requirements of the Expect request-header field.", useCase: "Used when a client sends 'Expect: 100-continue' but the server refuses." },
    { code: 418, message: "I'm a teapot", category: "Client Error", description: "This code was defined in 1998 as one of the traditional IETF April Fools' jokes, in RFC 2324.", useCase: "An Easter egg. Not used in real production APIs." },
    { code: 421, message: "Misdirected Request", category: "Client Error", description: "The request was directed at a server that is not able to produce a response.", useCase: "Used in HTTP/2 when a connection is reused for a domain it isn't authorized for." },
    { code: 422, message: "Unprocessable Entity", category: "Client Error", description: "The request was well-formed but was unable to be followed due to semantic errors.", useCase: "Used heavily in APIs (like Rails) when a payload is syntactically valid JSON, but fails business validation rules." },
    { code: 423, message: "Locked", category: "Client Error", description: "The resource that is being accessed is locked.", useCase: "Used in WebDAV to indicate a file is being edited by another user." },
    { code: 424, message: "Failed Dependency", category: "Client Error", description: "The request failed because it depended on another request and that request failed.", useCase: "Used in WebDAV when a PROPPATCH operation fails because a previous step failed." },
    { code: 425, message: "Too Early", category: "Client Error", description: "Indicates that the server is unwilling to risk processing a request that might be replayed.", useCase: "Used to mitigate replay attacks in TLS Early Data (0-RTT)." },
    { code: 426, message: "Upgrade Required", category: "Client Error", description: "The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field.", useCase: "Used to force a client to upgrade from HTTP/1.1 to HTTP/2." },
    { code: 428, message: "Precondition Required", category: "Client Error", description: "The origin server requires the request to be conditional.", useCase: "Used to require clients to send If-Match headers, preventing the 'lost update' problem." },
    { code: 429, message: "Too Many Requests", category: "Client Error", description: "The user has sent too many requests in a given amount of time.", useCase: "Used for API rate limiting." },
    { code: 431, message: "Request Header Fields Too Large", category: "Client Error", description: "The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large.", useCase: "Used when a client sends an extremely long Cookie header." },
    { code: 451, message: "Unavailable For Legal Reasons", category: "Client Error", description: "A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource.", useCase: "Used when content is blocked due to censorship or copyright takedowns (e.g., DMCA)." },

    // 5xx Server Error
    { code: 500, message: "Internal Server Error", category: "Server Error", description: "A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.", useCase: "The standard 'catch-all' response when a backend application crashes or throws an unhandled exception." },
    { code: 501, message: "Not Implemented", category: "Server Error", description: "The server either does not recognize the request method, or it lacks the ability to fulfil the request.", useCase: "Used when a client tries to use an HTTP method (like PROPFIND) the server doesn't support." },
    { code: 502, message: "Bad Gateway", category: "Server Error", description: "The server was acting as a gateway or proxy and received an invalid response from the upstream server.", useCase: "Commonly seen when a reverse proxy (like Nginx) cannot communicate with the backend application server." },
    { code: 503, message: "Service Unavailable", category: "Server Error", description: "The server cannot handle the request (because it is overloaded or down for maintenance). Generally, this is a temporary state.", useCase: "Used during planned downtime or when a server is completely overwhelmed with traffic." },
    { code: 504, message: "Gateway Timeout", category: "Server Error", description: "The server was acting as a gateway or proxy and did not receive a timely response from the upstream server.", useCase: "Seen when an API request takes too long, causing the API gateway or load balancer to drop the connection." },
    { code: 505, message: "HTTP Version Not Supported", category: "Server Error", description: "The server does not support the HTTP protocol version used in the request.", useCase: "Used if a client somehow tries to communicate using HTTP/0.9." },
    { code: 506, message: "Variant Also Negotiates", category: "Server Error", description: "Transparent content negotiation for the request results in a circular reference.", useCase: "Extremely rare; used in advanced content negotiation setups." },
    { code: 507, message: "Insufficient Storage", category: "Server Error", description: "The server is unable to store the representation needed to complete the request.", useCase: "Used in WebDAV when the server runs out of disk space." },
    { code: 508, message: "Loop Detected", category: "Server Error", description: "The server detected an infinite loop while processing the request.", useCase: "Used in WebDAV when following infinite redirect loops in directories." },
    { code: 510, message: "Not Extended", category: "Server Error", description: "Further extensions to the request are required for the server to fulfil it.", useCase: "Rarely used." },
    { code: 511, message: "Network Authentication Required", category: "Server Error", description: "The client needs to authenticate to gain network access.", useCase: "Used by captive portals (like hotel Wi-Fi) to force users to agree to terms or log in before granting internet access." }
];
